"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useAdminSave } from "./admin-submit";
import { AdminImageInput } from "./admin-image-input";
import { archiveCategory, saveCategory, toggleCategory } from "./category-actions";
import "./admin-manager.css";

export type AdminCategory = { id:string; name:string; nameTj?:string|null; slug:string; imageUrl?:string|null; sortOrder:number; isActive:boolean; archivedAt?:string|null };
const Pencil=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16.5-.8 4.3 4.3-.8L19 8.5 15.5 5 4 16.5ZM14 6.5l3.5 3.5"/></svg>;
function Form({ category, close }: { category?:AdminCategory; close:()=>void }) { const c=category; const router=useRouter(); const {submit,pending,error}=useAdminSave({action:saveCategory,onSuccess:()=>{close();router.refresh();},successTitle:c?"Категория обновлена":"Категория добавлена",errorTitle:"Не удалось сохранить категорию"}); return <form action={submit} aria-busy={pending} className="admin-form admin-editor">{c&&<input name="id" type="hidden" value={c.id}/>}<div className="admin-form-grid"><label>Название RU<input name="name" required maxLength={80} defaultValue={c?.name}/></label><label>Название TJ<input name="nameTj" maxLength={80} defaultValue={c?.nameTj??""}/></label><label>Slug<input name="slug" pattern="[a-z0-9-]+" maxLength={80} defaultValue={c?.slug??""} placeholder="Создаётся автоматически"/></label><label>Порядок<input name="sortOrder" type="number" min="0" defaultValue={c?.sortOrder??0}/></label></div><AdminImageInput prefix="categories" defaultValue={c?.imageUrl??""}/><label className="admin-switches"><input name="isActive" type="checkbox" defaultChecked={c?.isActive??true}/> Показывать в меню</label>{error&&<p className="admin-form-error" role="alert">{error}</p>}<button disabled={pending} className="admin-save">{pending?"Сохранение…":`✓ ${c?"Сохранить изменения":"Добавить категорию"}`}</button></form>; }
export function CategoryManager({ categories }: { categories:AdminCategory[] }) { const [current,setCurrent]=useState<AdminCategory|"new"|null>(null); const close=()=>setCurrent(null); return <section className="admin-workspace"><header className="admin-workspace-head"><div><p>КЛИЕНТСКОЕ МЕНЮ</p><h2>Категории</h2><span>Категория выглядит как у клиента, а карандаш открывает её редактор.</span></div><button className="admin-add" type="button" onClick={()=>setCurrent("new")}>＋ Добавить категорию</button></header><div className="admin-product-grid">{categories.map(category=><article className="admin-product-card" key={category.id}><div className="admin-product-image">{category.imageUrl?<img src={category.imageUrl} alt=""/>:<b>DIYOR<br/>BURGER</b>}<button type="button" aria-label={`Изменить ${category.name}`} onClick={()=>setCurrent(category)}><Pencil/></button></div><div><span>КАТЕГОРИЯ</span><em className={category.isActive?"ok":"off"}>{category.isActive?"Активна":"Выключена"}</em><h3>{category.name}</h3><p>{category.nameTj||"Название на таджикском ещё не добавлено"}</p><strong>/{category.slug}</strong></div></article>)}</div>{current&&<div className="admin-editor-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close();}}><section className="admin-editor-sheet" role="dialog" aria-modal="true"><header><div><p>{current==="new"?"НОВАЯ КАТЕГОРИЯ":"РЕДАКТИРОВАНИЕ"}</p><h2>{current==="new"?"Добавить категорию":current.name}</h2></div><button type="button" aria-label="Закрыть" onClick={close}>×</button></header><Form category={current==="new"?undefined:current} close={close}/>{current!=="new"&&<footer><form action={toggleCategory}><input name="id" type="hidden" value={current.id}/><input name="current" type="hidden" value={String(current.isActive)}/><button>{current.isActive?"Скрыть из меню":"Показывать в меню"}</button></form><form action={archiveCategory}><input name="id" type="hidden" value={current.id}/><button className="danger">Архивировать</button></form></footer>}</section></div>}</section>; }
