"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useAdminSave } from "./admin-submit";
import { addComboComponent, archiveCombo, archiveComboComponent, saveCombo } from "./combo-actions";
import { AdminImageInput } from "./admin-image-input";
import "./admin-manager.css";

type Category={id:string;name:string}; type Product={id:string;name:string;productType:string};
export type AdminCombo={id:string;categoryId:string;name:string;nameTj?:string|null;slug:string;description:string;descriptionTj?:string|null;basePriceDiram:number;imageUrl?:string|null;sortOrder:number;isAvailable:boolean;isActive:boolean;isPopular:boolean;components:{id:string;name:string;quantity:number;sortOrder:number}[]};
const Pencil=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16.5-.8 4.3 4.3-.8L19 8.5 15.5 5 4 16.5ZM14 6.5l3.5 3.5"/></svg>;
function ComboForm({combo,categories,close}:{combo?:AdminCombo;categories:Category[];close:()=>void}){const c=combo;const router=useRouter();const {submit,pending,error}=useAdminSave({action:saveCombo,onSuccess:()=>{close();router.refresh();},successTitle:c?"Комбо обновлено":"Комбо опубликовано",errorTitle:"Не удалось сохранить комбо"});return <form action={submit} aria-busy={pending} className="admin-form admin-editor">{c&&<input name="id" type="hidden" value={c.id}/>}<div className="admin-form-grid"><label>Категория<select name="categoryId" required defaultValue={c?.categoryId}>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Название RU<input name="name" required defaultValue={c?.name}/></label><label>Цена, сомони<input name="price" required inputMode="decimal" defaultValue={c?String(c.basePriceDiram/100):""}/></label><label>Порядок<input name="sortOrder" type="number" min="0" defaultValue={c?.sortOrder??0}/></label></div><label>Описание RU<textarea name="description" defaultValue={c?.description}/></label><details className="admin-more"><summary>Дополнительные поля</summary><label>Название TJ<input name="nameTj" defaultValue={c?.nameTj??""}/></label><label>Описание TJ<textarea name="descriptionTj" defaultValue={c?.descriptionTj??""}/></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" defaultValue={c?.slug??`combo-${Date.now()}`}/></label></details><AdminImageInput prefix="combos" defaultValue={c?.imageUrl??""}/><div className="admin-switches"><label><input name="isAvailable" type="checkbox" defaultChecked={c?.isAvailable??true}/> В наличии</label><label><input name="isActive" type="checkbox" defaultChecked={c?.isActive??true}/> Показывать клиентам</label><label><input name="isPopular" type="checkbox" defaultChecked={c?.isPopular??false}/> Популярное</label></div>{error&&<p className="admin-form-error" role="alert">{error}</p>}<button disabled={pending} className="admin-save">{pending?"Сохранение…":`✓ ${c?"Сохранить изменения":"Добавить комбо"}`}</button></form>}
function Components({combo,products}:{combo:AdminCombo;products:Product[]}){const router=useRouter();const {submit,pending,error}=useAdminSave({action:addComboComponent,onSuccess:()=>router.refresh(),successTitle:"Состав комбо обновлён",errorTitle:"Не удалось добавить блюдо в комбо"});return <section className="admin-pizza-sizes"><div><p>СОСТАВ НАБОРА</p><h3>Что входит в комбо</h3><span>Изменения состава сразу отображаются у клиента.</span></div>{combo.components.length?<ul className="admin-components">{combo.components.map(item=><li key={item.id}><span><b>{item.name}</b> × {item.quantity}</span><form action={archiveComboComponent}><input type="hidden" name="id" value={item.id}/><button type="submit" className="admin-icon-danger" aria-label={`Убрать ${item.name}`}>×</button></form></li>)}</ul>:<p>Состав пока пуст.</p>}<form action={submit} aria-busy={pending} className="admin-variant-row admin-variant-new"><input type="hidden" name="comboId" value={combo.id}/><label>Товар<select name="componentProductId" required>{products.filter(item=>item.id!==combo.id).map(item=><option value={item.id} key={item.id}>{item.name} · {item.productType}</option>)}</select></label><label>Количество<input name="quantity" type="number" min="1" defaultValue="1"/></label><label>Порядок<input name="sortOrder" type="number" min="0" defaultValue={combo.components.length}/></label><button type="submit" disabled={pending}>{pending?"Сохранение…":"＋ Добавить в состав"}</button></form>{error&&<p className="admin-form-error" role="alert">{error}</p>}</section>}
export function ComboManager({combos,categories,products}:{combos:AdminCombo[];categories:Category[];products:Product[]}){const[current,setCurrent]=useState<AdminCombo|"new"|null>(null);const close=()=>setCurrent(null);return <section className="admin-workspace"><header className="admin-workspace-head"><div><p>ВЫГОДНЫЕ НАБОРЫ</p><h2>Комбо</h2><span>Как у клиента: карточка, фото, цена и состав. Карандаш открывает редактирование.</span></div><button className="admin-add" type="button" onClick={()=>setCurrent("new")}>＋ Добавить комбо</button></header><div className="admin-product-grid">{combos.map(combo=><article className="admin-product-card" key={combo.id}><div className="admin-product-image">{combo.imageUrl?<img src={combo.imageUrl} alt=""/>:<b>DIYOR<br/>BURGER</b>}<button type="button" aria-label={`Изменить ${combo.name}`} onClick={()=>setCurrent(combo)}><Pencil/></button></div><div><span>КОМБО</span><em className={combo.isAvailable?"ok":"off"}>{combo.isAvailable?"В наличии":"Нет в наличии"}</em><h3>{combo.name}</h3><p>{combo.components.map(item=>`${item.name} × ${item.quantity}`).join(" · ")||"Состав пока не добавлен"}</p><strong>{combo.basePriceDiram/100} сом</strong></div></article>)}</div>{current&&<div className="admin-editor-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close();}}><section className="admin-editor-sheet" role="dialog" aria-modal="true"><header><div><p>{current==="new"?"НОВОЕ КОМБО":"РЕДАКТИРОВАНИЕ"}</p><h2>{current==="new"?"Добавить комбо":current.name}</h2></div><button type="button" aria-label="Закрыть" onClick={close}>×</button></header><ComboForm combo={current==="new"?undefined:current} categories={categories} close={close}/>{current!=="new"&&<><Components combo={current} products={products}/><footer><form action={archiveCombo}><input type="hidden" name="id" value={current.id}/><button className="danger">Архивировать</button></form></footer></>}</section></div>}</section>}
