"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/admin";
import { writeAdminAudit } from "@/lib/admin/audit-log";
import { somoniToDiram } from "@/lib/money";
import { createSupabaseServerClient } from "@/lib/supabase/server";

async function client(){await requireAdmin();const c=await createSupabaseServerClient();if(!c)throw new Error("ADMIN_DATA_UNAVAILABLE");return c;}
function refresh(){["/admin","/admin/delivery","/admin/settings","/admin/banners","/","/contacts","/checkout","/menu"].forEach(path=>revalidatePath(path));}

const zone=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(1).max(100),nameTj:z.string().trim().max(100),slug:z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),fee:z.string(),threshold:z.string(),sortOrder:z.coerce.number().int().min(0).max(9999),isActive:z.boolean()});
export async function saveZone(f:FormData){const d=zone.parse({id:String(f.get("id")??"")||undefined,name:String(f.get("name")??""),nameTj:String(f.get("nameTj")??""),slug:String(f.get("slug")??""),fee:String(f.get("fee")??""),threshold:String(f.get("threshold")??""),sortOrder:f.get("sortOrder")??0,isActive:f.get("isActive")==="on"});const fee=somoniToDiram(d.fee),threshold=somoniToDiram(d.threshold);if(fee===null||threshold===null)throw new Error("INVALID_DELIVERY_AMOUNT");const c=await client();const result=d.id?await c.from("delivery_zones").update({name:d.name,name_tj:d.nameTj||d.name,slug:d.slug,delivery_fee_diram:fee,free_delivery_threshold_diram:threshold,sort_order:d.sortOrder,is_active:d.isActive}).eq("id",d.id):await c.from("delivery_zones").insert({name:d.name,name_tj:d.nameTj||d.name,slug:d.slug,delivery_fee_diram:fee,free_delivery_threshold_diram:threshold,sort_order:d.sortOrder,is_active:d.isActive});if(result.error)throw new Error("ZONE_SAVE_FAILED");await writeAdminAudit(c,{action:d.id?"update":"create",entityType:"delivery_zone",entityId:d.id,afterData:{slug:d.slug,isActive:d.isActive}});refresh();}
export async function archiveZone(f:FormData){const id=z.string().uuid().parse(f.get("id"));const c=await client();const{error}=await c.from("delivery_zones").update({archived_at:new Date().toISOString(),is_active:false}).eq("id",id);if(error)throw new Error("ZONE_ARCHIVE_FAILED");await writeAdminAudit(c,{action:"archive",entityType:"delivery_zone",entityId:id});refresh();}

const settings=z.object({restaurantName:z.string().trim().min(1).max(120),whatsapp:z.string().trim().regex(/^\d{7,16}$/),phone1:z.string().trim().max(40),phone2:z.string().trim().max(40),instagram:z.string().trim().url().or(z.literal("")),mainAddress:z.string().trim().max(300),mainAddressTj:z.string().trim().max(300),pickupEnabled:z.boolean(),pickupAddress:z.string().trim().max(300),pickupAddressTj:z.string().trim().max(300),pickupNote:z.string().trim().max(500),pickupNoteTj:z.string().trim().max(500),mapUrl:z.string().trim().url().or(z.literal("")),openTime:z.string().regex(/^\d{2}:\d{2}$/).or(z.literal("")),closeTime:z.string().regex(/^\d{2}:\d{2}$/).or(z.literal("")),heroTitle:z.string().trim().max(160),heroTitleTj:z.string().trim().max(160),heroSubtitle:z.string().trim().max(300),heroSubtitleTj:z.string().trim().max(300),heroImage:z.string().trim().url().or(z.literal("")),benefit1:z.string().trim().max(80),benefit2:z.string().trim().max(80),benefit3:z.string().trim().max(80),benefit4:z.string().trim().max(80),promotionText:z.string().trim().max(300),promotionImage:z.string().trim().url().or(z.literal("")),cartEmptyTitle:z.string().trim().min(1).max(160),cartEmptyBody:z.string().trim().min(1).max(300),cartCheckoutLabel:z.string().trim().min(1).max(80),cartWhatsappLabel:z.string().trim().min(1).max(100)});
export async function saveSettings(f:FormData){const d=settings.parse({restaurantName:String(f.get("restaurantName")??""),whatsapp:String(f.get("whatsapp")??""),phone1:String(f.get("phone1")??""),phone2:String(f.get("phone2")??""),instagram:String(f.get("instagram")??""),mainAddress:String(f.get("mainAddress")??""),mainAddressTj:String(f.get("mainAddressTj")??""),pickupEnabled:f.get("pickupEnabled")==="on",pickupAddress:String(f.get("pickupAddress")??""),pickupAddressTj:String(f.get("pickupAddressTj")??""),pickupNote:String(f.get("pickupNote")??""),pickupNoteTj:String(f.get("pickupNoteTj")??""),mapUrl:String(f.get("mapUrl")??""),openTime:String(f.get("openTime")??""),closeTime:String(f.get("closeTime")??""),heroTitle:String(f.get("heroTitle")??""),heroTitleTj:String(f.get("heroTitleTj")??""),heroSubtitle:String(f.get("heroSubtitle")??""),heroSubtitleTj:String(f.get("heroSubtitleTj")??""),heroImage:String(f.get("heroImage")??""),benefit1:String(f.get("benefit1")??""),benefit2:String(f.get("benefit2")??""),benefit3:String(f.get("benefit3")??""),benefit4:String(f.get("benefit4")??""),promotionText:String(f.get("promotionText")??""),promotionImage:String(f.get("promotionImage")??""),cartEmptyTitle:String(f.get("cartEmptyTitle")??""),cartEmptyBody:String(f.get("cartEmptyBody")??""),cartCheckoutLabel:String(f.get("cartCheckoutLabel")??""),cartWhatsappLabel:String(f.get("cartWhatsappLabel")??"")});const c=await client();const payload={id:true,restaurant_name:d.restaurantName,order_whatsapp_number:d.whatsapp,contact_phone_1:d.phone1||null,contact_phone_2:d.phone2||null,instagram_url:d.instagram||null,main_address:d.mainAddress,main_address_tj:d.mainAddressTj||d.mainAddress,pickup_enabled:d.pickupEnabled,pickup_address:d.pickupAddress||null,pickup_address_tj:d.pickupAddressTj||d.pickupAddress||null,pickup_note:d.pickupNote||null,pickup_note_tj:d.pickupNoteTj||d.pickupNote||null,map_url:d.mapUrl||null,work_open_time:d.openTime||null,work_close_time:d.closeTime||null,hero_title:d.heroTitle||null,hero_title_tj:d.heroTitleTj||d.heroTitle||null,hero_subtitle:d.heroSubtitle||null,hero_subtitle_tj:d.heroSubtitleTj||d.heroSubtitle||null,hero_image_url:d.heroImage||null,benefit_labels:[d.benefit1,d.benefit2,d.benefit3,d.benefit4].filter(Boolean),promotion_text:d.promotionText||"При заказе 2 больших пиццы — маленькая пицца в подарок!",promotion_image_url:d.promotionImage||null,cart_empty_title:d.cartEmptyTitle,cart_empty_body:d.cartEmptyBody,cart_checkout_label:d.cartCheckoutLabel,cart_whatsapp_label:d.cartWhatsappLabel};const{error}=await c.from("restaurant_settings").upsert(payload);if(error)throw new Error("SETTINGS_SAVE_FAILED");await writeAdminAudit(c,{action:"update",entityType:"restaurant_settings",afterData:{pickupEnabled:d.pickupEnabled}});refresh();}

const banner=z.object({id:z.string().uuid().optional(),title:z.string().trim().min(1).max(160),titleTj:z.string().trim().max(160),body:z.string().trim().max(500),bodyTj:z.string().trim().max(500),imageUrl:z.string().trim().url().or(z.literal("")),targetUrl:z.string().trim().max(2048).refine(value=>!value||value.startsWith("/")||/^https?:\/\//.test(value)),sortOrder:z.coerce.number().int().min(0).max(9999),isActive:z.boolean()});
export async function saveBanner(f:FormData){const d=banner.parse({id:String(f.get("id")??"")||undefined,title:String(f.get("title")??""),titleTj:String(f.get("titleTj")??""),body:String(f.get("body")??""),bodyTj:String(f.get("bodyTj")??""),imageUrl:String(f.get("imageUrl")??""),targetUrl:String(f.get("targetUrl")??""),sortOrder:f.get("sortOrder")??0,isActive:f.get("isActive")==="on"});const c=await client();const payload={title:d.title,title_tj:d.titleTj||d.title,body:d.body||null,body_tj:d.bodyTj||d.body||null,image_url:d.imageUrl||null,target_url:d.targetUrl||null,sort_order:d.sortOrder,is_active:d.isActive};const result=d.id?await c.from("banners").update(payload).eq("id",d.id):await c.from("banners").insert(payload);if(result.error)throw new Error("BANNER_SAVE_FAILED");await writeAdminAudit(c,{action:d.id?"update":"create",entityType:"banner",entityId:d.id,afterData:{isActive:d.isActive}});refresh();}
export async function archiveBanner(f:FormData){const id=z.string().uuid().parse(f.get("id"));const c=await client();const{error}=await c.from("banners").update({archived_at:new Date().toISOString(),is_active:false}).eq("id",id);if(error)throw new Error("BANNER_ARCHIVE_FAILED");await writeAdminAudit(c,{action:"archive",entityType:"banner",entityId:id});refresh();}
