"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { archiveProduct, saveProduct, toggleProductAvailability } from "./product-actions";
import { AdminImageInput } from "./admin-image-input";
import type { AdminCategoryOption, AdminProduct } from "./product-manager";
import "./admin-manager.css";

const Pencil = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16.5-.8 4.3 4.3-.8L19 8.5 15.5 5 4 16.5ZM14 6.5l3.5 3.5"/></svg>;

function Editor({ product, categories, close }: { product?:AdminProduct; categories:AdminCategoryOption[]; close:()=>void }) {
  const [type,setType]=useState<AdminProduct["productType"]>(product?.productType??"NORMAL");
  const suggested=(kind:AdminProduct["productType"])=>categories.find((item)=>kind==="PIZZA"?/пицц/i.test(item.name):kind==="COMBO"?/комбо/i.test(item.name):!/пицц|комбо/i.test(item.name))?.id??categories[0]?.id;
  const [category,setCategory]=useState(product?.categoryId??suggested(type));
  return <form action={saveProduct} className="admin-form admin-editor" onSubmit={close}>{product&&<input type="hidden" name="id" value={product.id}/>}<div className="admin-form-grid"><label>Название блюда<input name="name" required defaultValue={product?.name} placeholder="Например, Чизбургер"/></label><label>Тип<select name="productType" value={type} onChange={(event)=>{const next=event.target.value as AdminProduct["productType"];setType(next);if(!product)setCategory(suggested(next));}}><option value="NORMAL">Блюдо</option><option value="PIZZA">Пицца</option><option value="COMBO">Комбо</option></select></label><label>Категория<select name="categoryId" value={category} onChange={(event)=>setCategory(event.target.value)}>{categories.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Цена, сомони<input name="price" required={type!=="PIZZA"} disabled={type==="PIZZA"} inputMode="decimal" defaultValue={product?.basePriceDiram==null?"":String(product.basePriceDiram/100)} placeholder={type==="PIZZA"?"Цены по размерам":"0"}/></label></div><label>Описание<textarea name="description" defaultValue={product?.description} placeholder="Это описание увидят клиенты"/></label><details className="admin-more"><summary>Дополнительные поля</summary><label>Название TJ<input name="nameTj" defaultValue={product?.nameTj??""}/></label><label>Описание TJ<textarea name="descriptionTj" defaultValue={product?.descriptionTj??""}/></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" defaultValue={product?.slug} placeholder="cheeseburger"/></label></details><AdminImageInput prefix="products" defaultValue={product?.imageUrl??""}/><div className="admin-switches"><label><input name="isAvailable" type="checkbox" defaultChecked={product?.isAvailable??true}/> В наличии</label><label><input name="isActive" type="checkbox" defaultChecked={product?.isActive??true}/> Показывать клиентам</label><label><input name="isPopular" type="checkbox" defaultChecked={product?.isPopular??false}/> Популярное</label></div><input name="sortOrder" type="hidden" value={product?.sortOrder??0}/><button className="admin-save">✓ {product?"Сохранить изменения":"Добавить товар"}</button></form>;
}

export function ProductWorkspace({ products, categories }: { products:AdminProduct[]; categories:AdminCategoryOption[] }) {
  const [current,setCurrent]=useState<AdminProduct|"new"|null>(null);
  const searchParams=useSearchParams();
  useEffect(()=>{if(searchParams.get("new")==="1")setCurrent("new")},[searchParams]);
  return <section className="admin-workspace"><header className="admin-workspace-head"><div><p>КАТАЛОГ ДЛЯ КЛИЕНТОВ</p><h2>Блюда и цены</h2><span>Нажмите карандаш, чтобы изменить именно эту карточку.</span></div><button className="admin-add" type="button" onClick={()=>setCurrent("new")}>＋ Добавить товар</button></header><div className="admin-product-grid">{products.map(product=><article className="admin-product-card" key={product.id}><div className="admin-product-image">{product.imageUrl?<img src={product.imageUrl} alt=""/>:<b>DIYOR<br/>BURGER</b>}<button type="button" aria-label={`Изменить ${product.name}`} onClick={()=>setCurrent(product)}><Pencil/></button></div><div><span>{product.productType==="PIZZA"?"Пицца":product.productType==="COMBO"?"Комбо":"Блюдо"}</span><em className={product.isAvailable?"ok":"off"}>{product.isAvailable?"В наличии":"Нет в наличии"}</em><h3>{product.name}</h3><p>{product.description||"Описание ещё не заполнено"}</p><strong>{product.basePriceDiram==null?"Цены по размерам":`${product.basePriceDiram/100} сом`}</strong></div></article>)}</div>{current&&<div className="admin-editor-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)setCurrent(null)}}><section className="admin-editor-sheet" role="dialog" aria-modal="true"><header><div><p>{current==="new"?"НОВЫЙ ТОВАР":"РЕДАКТИРОВАНИЕ"}</p><h2>{current==="new"?"Добавить товар":current.name}</h2></div><button type="button" aria-label="Закрыть" onClick={()=>setCurrent(null)}>×</button></header><Editor product={current==="new"?undefined:current} categories={categories} close={()=>setCurrent(null)}/>{current!=="new"&&<footer><form action={toggleProductAvailability}><input name="id" type="hidden" value={current.id}/><input name="current" type="hidden" value={String(current.isAvailable)}/><button>{current.isAvailable?"Снять с наличия":"Вернуть в наличие"}</button></form><form action={archiveProduct}><input name="id" type="hidden" value={current.id}/><button className="danger">Архивировать</button></form></footer>}</section></div>}</section>;
}
