import type { Category, Product } from "./types";

export const fixtureCategories: Category[] = [
  { id: "burgers", name: "Бургеры", nameTj:"Бургерҳо", slug: "burgers", imageUrl:"/images/burger-v1.png", isActive: true, sortOrder: 1 },
  { id: "hotdogs", name: "Хот-доги", nameTj:"Хот-догҳо", slug: "hotdogs", imageUrl:"/images/hotdog-v1.png", isActive: true, sortOrder: 2 },
  { id: "rolls", name: "Роллы", nameTj:"Роллҳо", slug: "rolls", imageUrl:"/images/burrito-v1.png", isActive: true, sortOrder: 3 },
  { id: "pizza", name: "Пицца", nameTj:"Пицца", slug: "pizza", imageUrl:"/images/pizza-v1.png", isActive: true, sortOrder: 4 },
  { id: "sides", name: "Гарниры", nameTj:"Иловаҳо", slug: "sides", imageUrl:"/images/fries-cola-v1.png", isActive: true, sortOrder: 5 },
  { id: "drinks", name: "Напитки", nameTj:"Нӯшокиҳо", slug: "drinks", imageUrl:"/images/fries-cola-v1.png", isActive: true, sortOrder: 6 },
  { id: "combos", name: "Комбо", nameTj:"Комбо", slug: "combos", imageUrl:"/images/fries-cola-v1.png", isActive: true, sortOrder: 7 },
];
export const fixtureProducts: Product[] = [
  { id:"hamburger",categoryId:"burgers",name:"Гамбургер",slug:"hamburger",productType:"NORMAL",description:"Сочная говяжья котлета, свежие овощи и фирменный соус.",ingredientsText:"говяжья котлета, овощи, фирменный соус",imageUrl:"/images/burger-v1.png",basePriceDiram:2200,isAvailable:true,isActive:true,isPopular:true,sortOrder:1 },
  { id:"cheeseburger",categoryId:"burgers",name:"Чизбургер",slug:"cheeseburger",productType:"NORMAL",description:"Сочная говяжья котлета, сыр, свежие овощи и фирменный соус.",ingredientsText:"говяжья котлета, сыр, овощи, фирменный соус",imageUrl:"/images/burger-v1.png",basePriceDiram:2500,isAvailable:true,isActive:true,isPopular:true,sortOrder:2 },
  { id:"bigburger",categoryId:"burgers",name:"Бигбургер",slug:"bigburger",productType:"NORMAL",description:"Две говяжьи котлеты, сыр, свежие овощи и фирменный соус.",ingredientsText:"две говяжьи котлеты, сыр, овощи",imageUrl:"/images/burger-v1.png",basePriceDiram:3500,isAvailable:true,isActive:true,isPopular:true,sortOrder:3 },
  { id:"hotdog",categoryId:"hotdogs",name:"Хот-дог",slug:"hotdog",productType:"NORMAL",description:"Сочная сосиска, булочка, кетчуп и горчица.",ingredientsText:"сосиска, булочка, кетчуп, горчица",imageUrl:"/images/hotdog-v1.png",basePriceDiram:1200,isAvailable:true,isActive:true,isPopular:false,sortOrder:1 },
  { id:"burrito-roll",categoryId:"rolls",name:"Ролл Буррито",slug:"burrito-roll",productType:"NORMAL",description:"Сочная говядина, свежие овощи и сыр в пшеничной лепёшке.",ingredientsText:"говядина, овощи, сыр, лепёшка",imageUrl:"/images/burrito-v1.png",basePriceDiram:2800,isAvailable:true,isActive:true,isPopular:true,sortOrder:1 },
  { id:"pepperoni",categoryId:"pizza",name:"Пицца Пепперони",slug:"pepperoni",productType:"PIZZA",description:"Пицца с пепперони, моцареллой и томатным соусом.",ingredientsText:"пепперони, моцарелла, томатный соус",imageUrl:"/images/pizza-v1.png",isAvailable:true,isActive:true,isPopular:true,sortOrder:1,variants:[{id:"pep-28",name:"28 см",priceDiram:6000,isActive:true,sortOrder:1},{id:"pep-30",name:"30 см",priceDiram:7000,isActive:true,sortOrder:2},{id:"pep-36",name:"36 см",priceDiram:8000,isActive:true,sortOrder:3}] },
  { id:"fries",categoryId:"sides",name:"Картофель фри",slug:"fries",productType:"NORMAL",description:"Золотистый и хрустящий картофель фри.",ingredientsText:"картофель, соль",imageUrl:"/images/fries-v2.png",basePriceDiram:1600,isAvailable:true,isActive:true,isPopular:true,sortOrder:1 },
  { id:"cola",categoryId:"drinks",name:"Coca-Cola 0.4",slug:"cola-04",productType:"NORMAL",description:"Классический освежающий напиток.",ingredientsText:"газированный напиток",imageUrl:"/images/cola-v2.png",basePriceDiram:800,isAvailable:true,isActive:true,isPopular:false,sortOrder:1 },
  { id:"combo-cheese",categoryId:"combos",name:"Комбо Чизбургер",slug:"combo-cheeseburger",productType:"COMBO",description:"Чизбургер + картофель фри + напиток 0.4.",ingredientsText:"чизбургер, картофель фри, напиток",imageUrl:"/images/fries-cola-v1.png",basePriceDiram:4300,isAvailable:true,isActive:true,isPopular:true,sortOrder:1,comboComponents:[{id:"cc1",name:"Чизбургер",quantity:1,sortOrder:1},{id:"cc2",name:"Картофель фри",quantity:1,sortOrder:2},{id:"cc3",name:"Напиток 0.4",quantity:1,sortOrder:3}] },
  { id:"combo-classic",categoryId:"combos",name:"Комбо Гамбургер",slug:"combo-hamburger",productType:"COMBO",description:"Гамбургер + картофель фри + напиток 0.4.",ingredientsText:"гамбургер, картофель фри, напиток",imageUrl:"/images/fries-cola-v1.png",basePriceDiram:4100,isAvailable:true,isActive:true,isPopular:true,sortOrder:0,comboComponents:[{id:"cl1",name:"Гамбургер",quantity:1,sortOrder:1},{id:"cl2",name:"Картофель фри",quantity:1,sortOrder:2},{id:"cl3",name:"Напиток 0.4",quantity:1,sortOrder:3}] },
  { id:"combo-big",categoryId:"combos",name:"Комбо Бигбургер",slug:"combo-bigburger",productType:"COMBO",description:"Бигбургер + картофель фри + напиток 0.4.",ingredientsText:"бигбургер, картофель фри, напиток",imageUrl:"/images/fries-cola-v1.png",basePriceDiram:5300,isAvailable:true,isActive:true,isPopular:false,sortOrder:2,comboComponents:[{id:"cb1",name:"Бигбургер",quantity:1,sortOrder:1},{id:"cb2",name:"Картофель фри",quantity:1,sortOrder:2},{id:"cb3",name:"Напиток 0.4",quantity:1,sortOrder:3}] },
  { id:"sold-out",categoryId:"sides",name:"Картофель по-деревенски",slug:"village-potatoes",productType:"NORMAL",description:"Картофельные дольки со специями.",ingredientsText:"картофель, специи",basePriceDiram:1300,isAvailable:false,isActive:true,isPopular:false,sortOrder:2 },
  { id:"hidden",categoryId:"burgers",name:"Архивный продукт",slug:"archived-product",productType:"NORMAL",description:"",ingredientsText:"",basePriceDiram:1000,isAvailable:true,isActive:false,isPopular:false,sortOrder:99 },
];
