export type Category = { id: string; name: string; nameTj?: string; slug: string; imageUrl?: string; isActive: boolean; sortOrder: number };
export type Variant = { id: string; name: string; nameTj?: string; priceDiram: number; isActive: boolean; isAvailable?: boolean; sortOrder: number };
export type ComboComponent = { id: string; name: string; nameTj?: string; description?: string; descriptionTj?: string; quantity: number; sortOrder: number };
export type ProductType = "NORMAL" | "PIZZA" | "COMBO";
export type Product = { id: string; categoryId: string; name: string; nameTj?: string; slug: string; productType: ProductType; description: string; descriptionTj?: string; ingredientsText: string; ingredientsTextTj?: string; imageUrl?: string; basePriceDiram?: number; isAvailable: boolean; isActive: boolean; isPopular: boolean; sortOrder: number; variants?: Variant[]; comboComponents?: ComboComponent[] };
export type MenuDataState<T> = { source: "supabase" | "development-fixture"; data: T } | { source: "unavailable"; data: null };
export type ProductFilters = { category?: string; minPriceDiram?: number; maxPriceDiram?: number; pizzaSize?: string; sort?: "popular" | "price_asc" | "price_desc" | "name" };
export type PublicRestaurantSettings = { restaurantName: string; contactPhone1?: string; contactPhone2?: string; instagramUrl?: string; mainAddress: string; pickupEnabled: boolean; pickupAddress?: string; pickupNote?: string; mapUrl?: string; workOpenTime?: string; workCloseTime?: string; heroTitle?: string; heroSubtitle?: string; heroImageUrl?: string };
export type PublicDeliveryZone = { id: string; name: string; isActive: boolean; deliveryFeeDiram: number; freeDeliveryThresholdDiram: number };
