import { notFound } from "next/navigation";
import { FoodImage } from "@/components/menu/food-image";
import { VariantSelector } from "@/components/menu/variant-selector";
import { formatSomoni } from "@/lib/money";
import { getProductBySlug } from "@/lib/menu/catalog";
import { productDisplayPrice } from "@/lib/menu/logic";
import { hasPricedVariants } from "@/lib/menu/variant-kind";
import { ProductPurchase } from "@/components/menu/product-purchase";
export default async function ProductPage({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const product=await getProductBySlug(slug); if(!product)notFound(); const price=productDisplayPrice(product); return <article className={`product-detail reference-product-detail ${product.productType.toLowerCase()}`}><div className="reference-hero product-detail-hero"><span className="hero-script">Вкуснее каждый день!</span><span className="hero-crown" aria-hidden="true">♕</span><h1>{product.name}</h1><p>{product.description}</p><FoodImage src={product.imageUrl} alt={product.name} compact/></div><section className="detail-description"><h2>Описание</h2><p className="lead">{product.description}</p></section><section><h2>{product.productType==="COMBO"?"Что входит в комбо":"Состав"}</h2>{product.productType==="COMBO"?<ol className="combo-components">{product.comboComponents?.map(c=><li key={c.id}><b>{c.name}</b><span>{c.quantity} шт.{c.description?` · ${c.description}`:""}</span></li>)}</ol>:<p>{product.ingredientsText}</p>}</section>{hasPricedVariants(product.productType)?<VariantSelector productType={product.productType === "DRINK" ? "DRINK" : "PIZZA"} productAvailable={product.isAvailable} productId={product.id} productName={product.name} variants={product.variants??[]}/>:<><div className="product-price"><strong>{formatSomoni(price??0)}</strong>{price !== undefined && product.oldPriceDiram != null && product.oldPriceDiram > price && <del>{formatSomoni(product.oldPriceDiram)}</del>}{product.isAvailable?<span>В наличии</span>:<span className="availability">Нет в наличии</span>}</div><ProductPurchase productId={product.id} productName={product.name} available={product.isAvailable}/></>}</article>; }
