import { AdminWorkspaceBar } from "@/features/admin/admin-workspace-bar";import { ComboManager,type AdminCombo } from "@/features/admin/combo-manager";import { requireAdmin } from "@/lib/auth/admin";import { createSupabaseServerClient } from "@/lib/supabase/server";
export default async function Page(){
 await requireAdmin();const c=await createSupabaseServerClient();
 if(!c)return <p className="notice">Данные недоступны</p>;
 const[{data:combos,error},{data:categories},{data:products}]=await Promise.all([c.from("products").select("*,combo_components(*)").eq("product_type","COMBO").is("archived_at",null).order("sort_order"),c.from("categories").select("id,name").is("archived_at",null).order("sort_order"),c.from("products").select("id,name,product_type").is("archived_at",null).eq("is_active",true).order("sort_order")]);
 if(error)return <p className="notice">Данные недоступны</p>;
 const list=(combos??[]).map((x:Record<string,unknown>):AdminCombo=>{const raw=Array.isArray(x.combo_components)?x.combo_components as Record<string,unknown>[]:[];return {id:String(x.id),categoryId:String(x.category_id),name:String(x.name),nameTj:x.name_tj as string|undefined,slug:String(x.slug),description:String(x.description??""),descriptionTj:x.description_tj as string|undefined,basePriceDiram:Number(x.base_price_diram),imageUrl:x.image_url as string|undefined,sortOrder:Number(x.sort_order),isAvailable:Boolean(x.is_available),isActive:Boolean(x.is_active),isPopular:Boolean(x.is_popular),components:raw.filter(y=>!y.archived_at).map(y=>({id:String(y.id),name:String(y.name),quantity:Number(y.quantity),sortOrder:Number(y.sort_order)})).sort((a,b)=>a.sortOrder-b.sortOrder)}});
 return <><AdminWorkspaceBar title="Комбо"/><ComboManager combos={list} categories={(categories??[]).map((x:Record<string,unknown>)=>({id:String(x.id),name:String(x.name)}))} products={(products??[]).map((x:Record<string,unknown>)=>({id:String(x.id),name:String(x.name),productType:String(x.product_type)}))}/></>
}
